version: "3.8"

services:
  ethmysql:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.role == mysql
    volumes:
      - /etc/localtime:/etc/localtime
      - mysql_data:/var/lib/mysql
      - /opt/liveness/config/mysql/conf/my.cnf:/etc/my.cnf
      - /opt/liveness/config/mysql/init:/docker-entrypoint-initdb.d/
    networks:
      - meta

  execute1:
    image: tscel/geth:v1.13-base-v5
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 1
    volumes:
      - /opt/liveness/config:/root/config
      - execute1_data:/root/gethdata
      - /opt/liveness/execute.sh:/usr/local/bin/execution.sh
    networks:
      - meta

  execute2:
    image: tscel/geth:v1.13-base-v5
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 2
    volumes:
      - /opt/liveness/config:/root/config
      - execute2_data:/root/gethdata
      - /opt/liveness/execute.sh:/usr/local/bin/execution.sh
    networks:
      - meta

  execute3:
    image: tscel/geth:v1.13-base-v5
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 3
    volumes:
      - /opt/liveness/config:/root/config
      - execute3_data:/root/gethdata
      - /opt/liveness/execute.sh:/usr/local/bin/execution.sh
    networks:
      - meta

  execute4:
    image: tscel/geth:v1.13-base-v5
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 4
    volumes:
      - /opt/liveness/config:/root/config
      - execute4_data:/root/gethdata
      - /opt/liveness/execute.sh:/usr/local/bin/execution.sh
    networks:
      - meta

  execute5:
    image: tscel/geth:v1.13-base-v5
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 5
    volumes:
      - /opt/liveness/config:/root/config
      - execute5_data:/root/gethdata
      - /opt/liveness/execute.sh:/usr/local/bin/execution.sh
    networks:
      - meta

  attacker1:
    image: tscel/bunnyfinder:latest
    entrypoint: attacker --config /root/config.toml --strategy ext_withholding --max-hack-idx 85 --logpath /root/attackerdata/d.log --loglevel info
    environment:
      - NAME=attacker1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 1
    depends_on:
      - beacon1
      - beacon2
    volumes:
      - /opt/liveness/config/attacker-config.toml:/root/config.toml
      - /opt/liveness/config/strategy-empty.json:/root/strategy.json
      - attacker1_data:/root/attackerdata
    networks:
      - meta

  attacker2:
    image: tscel/bunnyfinder:latest
    entrypoint: attacker --config /root/config.toml --strategy ext_withholding --max-hack-idx 85 --logpath /root/attackerdata/d.log --loglevel info
    environment:
      - NAME=attacker2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 2
    depends_on:
      - beacon1
      - beacon2
    volumes:
      - /opt/liveness/config/attacker-honest-config.toml:/root/config.toml
      - /opt/liveness/config/strategy-empty.json:/root/strategy.json
      - attacker2_data:/root/attackerdata
    networks:
      - meta

  beacon1:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/beacon.sh
    env_file:
      - .env
    environment:
      - PEER_SERVICES=beacon2,beacon3,beacon4,beacon5
      - EXECUTE=execute1
      - MAXPEERS=70
      - ATTACKER_SERVICE_URL=http://attacker1:10000
      - P2PKEY=0692f57d5ddf34d0f2649d968bf82e2dda69d1f435a7f3a7a26d81a1a11e687b
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 1
    ports:
      - target: 13000
        published: 13000
        protocol: tcp
        mode: host
    volumes:
      - /opt/liveness/beacon.sh:/usr/local/bin/beacon.sh
      - /opt/liveness/config:/root/config
      - beacon1_data:/root/beacondata
    depends_on:
      - execute1
    networks:
      - meta

  beacon2:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/beacon.sh
    environment:
      - PEER_SERVICES=beacon1,beacon3,beacon4,beacon5
      - EXECUTE=execute2
      - MAXPEERS=70
      - ATTACKER_SERVICE_URL=http://attacker1:10000
      - P2PKEY=9edcc99209261dfca0d5b79cd1ff43e2e30005c629337d921711bb77fa816dd3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 2
    ports:
      - target: 13000
        published: 13000
        protocol: tcp
        mode: host
    volumes:
      - /opt/liveness/beacon.sh:/usr/local/bin/beacon.sh
      - /opt/liveness/config:/root/config
      - beacon2_data:/root/beacondata
    depends_on:
      - execute2
    networks:
      - meta

  beacon3:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/beacon.sh
    environment:
      - PEER_SERVICES=beacon1,beacon2,beacon4,beacon5
      - EXECUTE=execute3
      - MAXPEERS=70
      - ATTACKER_SERVICE_URL=http://attacker2:10000
      - P2PKEY=9513c7244d2983d47b54df161a3fc981b946944d7c2bba338588e0ab7dc40777
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 3
    ports:
      - target: 13000
        published: 13000
        protocol: tcp
        mode: host
    volumes:
      - /opt/liveness/beacon.sh:/usr/local/bin/beacon.sh
      - /opt/liveness/config:/root/config
      - beacon3_data:/root/beacondata
    depends_on:
      - execute3
    networks:
      - meta

  beacon4:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/beacon.sh
    environment:
      - PEER_SERVICES=beacon1,beacon2,beacon3,beacon5
      - EXECUTE=execute4
      - MAXPEERS=70
      - ATTACKER_SERVICE_URL=http://attacker2:10000
      - P2PKEY=c118a256c6aa383b0d02a6ac25139566bc042c837f248e71aa38fcd961dac8aa
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 4
    ports:
      - target: 13000
        published: 13000
        protocol: tcp
        mode: host
    volumes:
      - /opt/liveness/beacon.sh:/usr/local/bin/beacon.sh
      - /opt/liveness/config:/root/config
      - beacon4_data:/root/beacondata
    depends_on:
      - execute4
    networks:
      - meta

  beacon5:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/beacon.sh
    environment:
      - PEER_SERVICES=beacon1,beacon2,beacon3,beacon4
      - EXECUTE=execute5
      - MAXPEERS=70
      - ATTACKER_SERVICE_URL=http://attacker2:10000
      - P2PKEY=f01cd004ad47970f7ca62dadb1921a173c9686cf11e963c04d8a81f36322fd9f
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 5
    ports:
      - target: 13000
        published: 13000
        protocol: tcp
        mode: host
    volumes:
      - /opt/liveness/beacon.sh:/usr/local/bin/beacon.sh
      - /opt/liveness/config:/root/config
      - beacon5_data:/root/beacondata
    depends_on:
      - execute5
    networks:
      - meta

  validator1:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=86
      - VALIDATORS_INDEX=0
      - BEACONRPC=beacon1:4000
      - ATTACKER_SERVICE_URL=http://attacker1:10000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 1
    volumes:
      - /opt/liveness/validator.sh:/usr/local/bin/validator.sh
      - /opt/liveness/config:/root/config
      - validator1_data:/root/validatordata
    depends_on:
      - beacon1
    networks:
      - meta

  validator2:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=50
      - VALIDATORS_INDEX=86
      - BEACONRPC=beacon2:4000
      - ATTACKER_SERVICE_URL=http://attacker1:10000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 2
    volumes:
      - /opt/liveness/validator.sh:/usr/local/bin/validator.sh
      - /opt/liveness/config:/root/config
      - validator2_data:/root/validatordata
    depends_on:
      - beacon2
    networks:
      - meta

  validator3:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=51
      - VALIDATORS_INDEX=136
      - BEACONRPC=beacon3:4000
      - ATTACKER_SERVICE_URL=http://attacker2:10000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 3
    volumes:
      - /opt/liveness/validator.sh:/usr/local/bin/validator.sh
      - /opt/liveness/config:/root/config
      - validator3_data:/root/validatordata
    depends_on:
      - beacon3
    networks:
      - meta

  validator4:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=51
      - VALIDATORS_INDEX=187
      - BEACONRPC=beacon4:4000
      - ATTACKER_SERVICE_URL=http://attacker2:10000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 4
    volumes:
      - /opt/liveness/validator.sh:/usr/local/bin/validator.sh
      - /opt/liveness/config:/root/config
      - validator4_data:/root/validatordata
    depends_on:
      - beacon4
    networks:
      - meta

  validator5:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=18
      - VALIDATORS_INDEX=238
      - BEACONRPC=beacon5:4000
      - ATTACKER_SERVICE_URL=http://attacker2:10000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 5
    volumes:
      - /opt/liveness/validator.sh:/usr/local/bin/validator.sh
      - /opt/liveness/config:/root/config
      - validator5_data:/root/validatordata
    depends_on:
      - beacon5
    networks:
      - meta

networks:
  meta:
    driver: overlay
    ipam:
      config:
        - subnet: 172.86.1.0/24

volumes:
  mysql_data:
    driver: local
  execute1_data:
    driver: local
  execute2_data:
    driver: local
  execute3_data:
    driver: local
  execute4_data:
    driver: local
  execute5_data:
    driver: local
  attacker1_data:
    driver: local
  attacker2_data:
    driver: local
  beacon1_data:
    driver: local
  beacon2_data:
    driver: local
  beacon3_data:
    driver: local
  beacon4_data:
    driver: local
  beacon5_data:
    driver: local
  validator1_data:
    driver: local
  validator2_data:
    driver: local
  validator3_data:
    driver: local
  validator4_data:
    driver: local
  validator5_data:
    driver: local
