version: "3.8"

services:
  ethmysql:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    deploy:
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.role == mysql
    volumes:
      - /etc/localtime:/etc/localtime
      - /opt/liveness/data/mysql/data:/var/lib/mysql
      - /opt/liveness/config/mysql/conf/my.cnf:/etc/my.cnf
      - /opt/liveness/config/mysql/init:/docker-entrypoint-initdb.d/
    networks:
      - meta

  execute1:
    image: tscel/geth:v1.13-base-v5
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 1
    volumes:
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/execute1:/root/gethdata
      - /opt/liveness/execute.sh:/usr/local/bin/execution.sh
    networks:
      - meta

  execute2:
    image: tscel/geth:v1.13-base-v5
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 2
    volumes:
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/execute2:/root/gethdata
      - /opt/liveness/execute.sh:/usr/local/bin/execution.sh
    networks:
      - meta

  execute3:
    image: tscel/geth:v1.13-base-v5
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 3
    volumes:
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/execute3:/root/gethdata
      - /opt/liveness/execute.sh:/usr/local/bin/execution.sh
    networks:
      - meta

  execute4:
    image: tscel/geth:v1.13-base-v5
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 4
    volumes:
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/execute4:/root/gethdata
      - /opt/liveness/execute.sh:/usr/local/bin/execution.sh
    networks:
      - meta

  execute5:
    image: tscel/geth:v1.13-base-v5
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 5
    volumes:
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/execute5:/root/gethdata
      - /opt/liveness/execute.sh:/usr/local/bin/execution.sh
    networks:
      - meta

  attacker1:
    image: tscel/bunnyfinder:latest
    entrypoint: attacker --config /root/config.toml --strategy ext_withholding --max-hack-idx 85 --logpath /root/attackerdata/d.log --loglevel info
    environment:
      - NAME=attacker1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 1
    volumes:
      - /opt/liveness/config/attacker-config.toml:/root/config.toml
      - /opt/liveness/config/strategy-empty.json:/root/strategy.json
      - /opt/liveness/data/attacker1:/root/attackerdata
    networks:
      - meta

  attacker2:
    image: tscel/bunnyfinder:latest
    entrypoint: attacker --config /root/config.toml --strategy ext_withholding --max-hack-idx 85 --logpath /root/attackerdata/d.log --loglevel info
    environment:
      - NAME=attacker2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 2
    volumes:
      - /opt/liveness/config/attacker-normal.toml:/root/config.toml
      - /opt/liveness/config/strategy-empty.json:/root/strategy.json
      - /opt/liveness/data/attacker2:/root/attackerdata
    networks:
      - meta

  beacon1:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/beacon.sh
    env_file:
      - .env
    environment:
      - PEER_SERVICES=beacon2,beacon3,beacon4,beacon5
      - EXECUTE=execute1
      - MAXPEERS=70
      - ATTACKER_SERVICE_URL=http://attacker1:10000
      - P2PKEY=${P2PKEY_beacon1}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 1
    volumes:
      - /opt/liveness/beacon.sh:/usr/local/bin/beacon.sh
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/beacon1:/root/beacondata
    depends_on:
      - execute1
    networks:
      - meta

  beacon2:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/beacon.sh
    environment:
      - PEER_SERVICES=beacon1,beacon3,beacon4,beacon5
      - EXECUTE=execute2
      - MAXPEERS=70
      - ATTACKER_SERVICE_URL=http://attacker1:10000
      - P2PKEY=${P2PKEY_beacon2}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 2
    volumes:
      - /opt/liveness/beacon.sh:/usr/local/bin/beacon.sh
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/beacon2:/root/beacondata
    depends_on:
      - execute2
    networks:
      - meta

  beacon3:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/beacon.sh
    environment:
      - PEER_SERVICES=beacon1,beacon2,beacon4,beacon5
      - EXECUTE=execute3
      - MAXPEERS=70
      - ATTACKER_SERVICE_URL=http://attacker2:10000
      - P2PKEY=${P2PKEY_beacon3}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 3
    volumes:
      - /opt/liveness/beacon.sh:/usr/local/bin/beacon.sh
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/beacon3:/root/beacondata
    depends_on:
      - execute3
    networks:
      - meta

  beacon4:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/beacon.sh
    environment:
      - PEER_SERVICES=beacon1,beacon2,beacon3,beacon5
      - EXECUTE=execute4
      - MAXPEERS=70
      - ATTACKER_SERVICE_URL=http://attacker2:10000
      - P2PKEY=${P2PKEY_beacon4}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 4
    volumes:
      - /opt/liveness/beacon.sh:/usr/local/bin/beacon.sh
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/beacon4:/root/beacondata
    depends_on:
      - execute4
    networks:
      - meta

  beacon5:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/beacon.sh
    environment:
      - PEER_SERVICES=beacon1,beacon2,beacon3,beacon4
      - EXECUTE=execute5
      - MAXPEERS=70
      - ATTACKER_SERVICE_URL=http://attacker2:10000
      - P2PKEY=${P2PKEY_beacon5}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 5
    volumes:
      - /opt/liveness/beacon.sh:/usr/local/bin/beacon.sh
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/beacon5:/root/beacondata
    depends_on:
      - execute5
    networks:
      - meta

  validator1:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=86
      - VALIDATORS_INDEX=0
      - BEACONRPC=beacon1:4000
      - ATTACKER_SERVICE_URL=http://attacker1:10000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 1
    volumes:
      - /opt/liveness/validator.sh:/usr/local/bin/validator.sh
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/validator1:/root/validatordata
    depends_on:
      - beacon1
    networks:
      - meta

  validator2:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=50
      - VALIDATORS_INDEX=86
      - BEACONRPC=beacon2:4000
      - ATTACKER_SERVICE_URL=http://attacker1:10000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 2
    volumes:
      - /opt/liveness/validator.sh:/usr/local/bin/validator.sh
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/validator2:/root/validatordata
    depends_on:
      - beacon2
    networks:
      - meta

  validator3:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=51
      - VALIDATORS_INDEX=136
      - BEACONRPC=beacon3:4000
      - ATTACKER_SERVICE_URL=http://attacker2:10000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 3
    volumes:
      - /opt/liveness/validator.sh:/usr/local/bin/validator.sh
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/validator3:/root/validatordata
    depends_on:
      - beacon3
    networks:
      - meta

  validator4:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=51
      - VALIDATORS_INDEX=187
      - BEACONRPC=beacon4:4000
      - ATTACKER_SERVICE_URL=http://attacker2:10000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 4
    volumes:
      - /opt/liveness/validator.sh:/usr/local/bin/validator.sh
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/validator4:/root/validatordata
    depends_on:
      - beacon4
    networks:
      - meta

  validator5:
    image: tscel/bf.prysm:v5.2.0-liveness
    entrypoint: /usr/local/bin/validator.sh
    environment:
      - VALIDATORS_NUM=18
      - VALIDATORS_INDEX=238
      - BEACONRPC=beacon5:4000
      - ATTACKER_SERVICE_URL=http://attacker2:10000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
      placement:
        constraints:
          - node.labels.service-set == 5
    volumes:
      - /opt/liveness/validator.sh:/usr/local/bin/validator.sh
      - /opt/liveness/config:/root/config
      - /opt/liveness/data/validator5:/root/validatordata
    depends_on:
      - beacon5
    networks:
      - meta

networks:
  meta:
    driver: overlay
    ipam:
      config:
        - subnet: 172.86.1.0/24